-- SQL Dump of Datatal.accdb
-- generated by MDB Viewer 2.3.1
-- optimized for MySQL

SET NAMES 'UTF8';



DROP TABLE IF EXISTS `Cities`;

CREATE TABLE `Cities` (
    `CodeCity` INTEGER PRIMARY KEY,
    `NameCity` VARCHAR(255)
) CHARACTER SET 'UTF8';


-- The free trial of MDB ACCDB Viewer exports only half of the records in each table.
INSERT INTO `Cities`(`CodeCity`,`NameCity`)
VALUES(1,'תל אביב'),
      (2,'רמת גן'),
      (3,'קרית אונו'),
      (4,'גבעת שמואל'),
      (5,'גני תקוה'),
      (6,'פתח תקווה'),
      (7,'ירושליים'),
      (8,'חיפה'),
      (9,'אילת'),
      (10,'רחובות'),
      (11,'טבריה'),
      (12,'שהם'),
      (13,'אשקלון'),
      (14,'אשדוד'),
      (15,'נצרת'),
      (16,'דימונה'),
      (17,'נהריה'),
      (18,'הרצליה'),
      (19,'ראשון לציון'),
      (20,'חולון');



DROP TABLE IF EXISTS `Exercises`;

CREATE TABLE `Exercises` (
    `NumberExercises` INTEGER PRIMARY KEY,
    `NameExercises` VARCHAR(255),
    `Description` VARCHAR(255),
    `WorkOn` INTEGER,
    `levelThis` INTEGER
) CHARACTER SET 'UTF8';


-- The free trial of MDB ACCDB Viewer exports only half of the records in each table.
INSERT INTO `Exercises`(`NumberExercises`,`NameExercises`,`Description`,`WorkOn`,`levelThis`)
VALUES(2,'לג פרס','\nלשבת על המכונה עם גב על תמיכה מרופד. מקום על הרגליים. הרחבת ירכיים וברכיים. שחרר את ידית המעגן ואת ידיות אחיזה לצדדים.\nמזחלת תחתון על ידי כופפים מתנים וברכיים עד הברכיים רק קצר של גמישות מלאה. חזור על ידי הרחבת הברכיים והירכיים. חזור על כך.',1,2),
      (3,'דדליפט קלאסי','\nעם רגליים שטוחות מתחת לבר, מתיישב למטה לתפוס בר עם רוחב הכתף או מעט רחב יותר יד או אחיזה מעורבת.\nהרם בר על ידי הרחבת ירכיים וברכיים להארכה מלאה. משוך את הכתפיים בחזרה למעלה במעלית אם מעוגל. חזור וחזור.',1,1),
      (4,'לחיצת חזה כנגד מוט בשכיבה',NULL,2,1),
      (5,'פרפר',NULL,2,1),
      (6,'מתח בתוספת משקל',NULL,3,1),
      (7,'משיגת פולי עליון לפנים באחיזה רחבה בישיבה',NULL,3,2),
      (8,'חטירה בהטיה לפנים',NULL,3,2),
      (9,'לחיצת כתפיים כנגד מוט באחיזה רחבה בעמידה',NULL,4,2),
      (10,'הרחקת כתפיים כנגד משקולית יד בעמידה',NULL,4,1),
      (11,'מקבילים באחיזה צרה בתוספת משקל',NULL,5,2),
      (12,'פשיטת מרפקים כנגד מוט',NULL,5,1),
      (13,'כפיפת מרפקים כנגד מוט בעמידה',NULL,6,2),
      (14,'כפיפת גו במכונה ייעודית',NULL,7,1),
      (15,'כפיפות בטן',NULL,7,2),
      (16,'חתירה עם מוט בעמידה','דגשים לביצוע נכון:\n1.אחיזה צרה,מרפקים קרובים לגוף.\n2.מרפק מוביל תנועה.\n3.בזמן ביצוע תרגיל יש להקפיד על גו ישר. \n4.הוצאת אויר בזמן מאמץ(חתירה)והכנסת אויר בזמן יישור ידיים. \nהערה:יש עומס גדול על גו תחתון לא מומלץ למתאמנים מתחילים או לסובלים מכאבי גו.',3,1),
      (17,'חתירה עם מוט אולימפי בעמידה','דגשים לביצוע נכון:\n1.אחיזה צרה,מרפקים קרובים לגוף.\n2.מרפק מוביל תנועה.\n3.בזמן ביצוע תרגיל יש להקפיד על גו ישר. \n4.הוצאת אויר בזמן מאמץ(חתירה)והכנסת אויר בזמן יישור ידיים. \nהערה:יש עומס גדול על גו תחתון לא מומלץ למתאמנים מתחילים או לסובלים מכאבי גו.',3,4),
      (18,'pull over בשכיבה עם מוט','1.בזמן ביצוע התרגיל הידיים מעט כופפות על מנת להפעיל מייצבים במרפק.\n2.יש לשים לב על גב תחתון שהוא לא עולה.\n3.הוצאת אויר בזמן מאמץ(משיכה)והכנסת אויר בזמן חזרה לעמדת המוצא.',3,3),
      (19,'משיכת פולי עליון באחיזה רחבה לחזה','דגשים לביצוע נכון:\n1.הגו נוטה מעט לאחור.\n2.התנועה במרפק לכיוון צלעות תחתונות.\n3.הורדת המוט עד חזה עליון.\n4.בזמן ביצוע תרגיל יש נטייה לבצע הרמת שכמות וכך יופעל טרפז עליון באופן דומיננטי יותר לכן מומלץ לבצע הורדת שכמות למטה .',3,5),
      (1,'סקוואט כנגד מוט','מקמו את הרגליים בפיסוק גדול בקצת מרוחב הכתפיים. את אצבעות הרגליים יש להטות כלפי חוץ, בערך 30-45 מעלות.',1,1),
      (20,'משיכת פולי עליון באחיזה הפוכה','1.הגו נוטה מעט לאחור.\n2.התנועה במרפק לכיוון צלעות תחתונות.\n3.הורדת משולש עד חזה עליון.\n4.בזמן ביצוע התרגיל יש נטייה לבצע הרמת שכמות וכך יופעל טרפז עליון באופן דומיננטי יותר לכן מומלץ לבצע הורדת שכמות למטה .\n5.בתרגיל מרפק מוביל תנועה.',3,6),
      (21,'חתירה מכשיר','1.אחיזה צרה,מרפקים מקבילים אחד לשני וקרובים לצדי גוף.\n2.מרפק מוביל תנועה.\n3.בזמן ביצוע התרגיל יש להקפיד על גו ישר ומוטה מעט לאחור.\n4.הכרית התומכת מלפנים ממוקמת בבית החזה. \n5.הוצאת אויר בזמן מאמץ(חתירה)והכנסת  אויר בזמן יישור ידיים.',3,0),
      (22,'שכיבות סמיכה','1.כפות ידיים מעט מעבר לרוחב כתפיים\n2.בזמן ירידה,ידיים צריכות להיות בקו החזה.\n3.מרפק מוביל תנועה.\n4.בסיום התנועה לא לנעול מרפקים.\n5.בזמן ביצוע התרגיל לשמור על גו ישר.',2,2),
      (23,'שכיבות סמיכה שיפוע חיובי','1.כפות ידיים מעט מעבר לרוחב כתפיים\n2.בזמן ירידה,ידיים צריכות להיות בקו החזה.\n3.מרפק מוביל תנועה\n4.בסיום התנועה לא לנעול מרפקים.\n5.בזמן ביצוע התרגיל לשמור על גו ישר.',2,3),
      (24,'שכיבות סמיכה שיפוע שלילי','1.כפות ידיים מעט מעבר לרוחב כתפיים\n2.בזמן ירידה,ידיים צריכות להיות בקו החזה.\n3.מרפק מוביל תנועה\n4.בסיום התנועה לא לנעול מרפקים.\n5.בזמן ביצוע התרגיל לשמור על גו ישר.',2,4),
      (25,'מקבילים באחיזה רחבה','1.כפות ידיים מעט מעבר לרוחב כתפיים\n2.מרפק מוביל תנועה.\n3.בסיום התנועה לא לנעול מרפקים.\n4.בזמן ביצוע התרגיל גו מוטה טיפה קדימה.\n5.הוצאת אויר בזמן מאמץ(עליה)והכנסת אויר בזמן ירידה.',2,4),
      (26,'שכיבות סמיכה על כדור','1.כפות ידיים מעט מעבר לרוחב כתפיים\n2.בזמן ירידה,ידיים צריכות להיות בקו החזה.\n3.מרפק מוביל תנועה.\n4.בסיום התנועה לא לנעול מרפקים.\n5.בזמן ביצוע התרגיל לשמור על גו ישר.\n6.הוצאת אויר בזמן מאמץ(עליה)והכנסת אויר בזמן ירידה.',2,5),
      (27,'שכיבות סמיכה על בוסו','1.כפות ידיים מעט מעבר לרוחב כתפיים\n2.בזמן ירידה,ידיים צריכות להיות בקו החזה.\n3.מרפק מוביל תנועה.\n4.בסיום התנועה לא לנעול מרפקים.\n5.בזמן ביצוע התרגיל לשמור על גו ישר.\n6.הוצאת אויר בזמן מאמץ(עליה)והכנסת אויר בזמן ירידה.',2,6),
      (28,'פשיטת מרפק עם גומיה','1.בזמן ביצוע תרגיל מומלץ שרגל אחד תהיה מעט קדימה או פיסוק ברגליים,על מנת ליצב גוף יותר טוב.\n2.בזמן ביצוע תרגיל חשוב להקפיד שאין תנועה בעמוד השדרה.\n3.חשוב לשמור על טווח תנועה מלא,לא לנעול מרפק בישור.',2,6),
      (29,'הרחקת כתפיים Cross over','1.תחילת התנועה הידיים ממוקמת בצידי הגוף.\n2.בזמן ביצוע תרגיל אין תנועה במרפק.\n3.בזמן ביצוע תרגיל יש לכופף טיפה את מרפקים על מנת להפעיל את מייצבים יותר חזק.',4,2),
      (30,'הרחקת כתף ב Cross over','1.תחילת התנועה הידיים ממוקמת בצידי הגוף.',4,3),
      (31,'חתירה(פולי תחתון)ב Cross over','תחילת התנועה הידיים ממוקמת בצידי הגוף.\n2.בתרגיל זה יש להקפיד על פישוק קל ברגליים.\n3.בזמן ביצוע תרגיל יש לכופף טיפה את ברכיים על מנת להפעיל את מייצבים יותר חזק.',4,4);



DROP TABLE IF EXISTS `ExercisesTrain`;

CREATE TABLE `ExercisesTrain` (
    `CodeCoaching` INTEGER,
    `CodeExercises` INTEGER,
    `NumBack` VARCHAR(255),
    `RetaNumber` VARCHAR(255),
    `WorkOnCode` INTEGER
) CHARACTER SET 'UTF8';


-- The free trial of MDB ACCDB Viewer exports only half of the records in each table.
INSERT INTO `ExercisesTrain`(`CodeCoaching`,`CodeExercises`,`NumBack`,`RetaNumber`,`WorkOnCode`)
VALUES(309238871,17,'לא צויין','תחזור על התרגיל 30',1),
      (314713652,1,'23','6',1);



DROP TABLE IF EXISTS `Gender`;

CREATE TABLE `Gender` (
    `CodeGender` INTEGER PRIMARY KEY,
    `NameGender` VARCHAR(255)
) CHARACTER SET 'UTF8';


-- The free trial of MDB ACCDB Viewer exports only half of the records in each table.
INSERT INTO `Gender`(`CodeGender`,`NameGender`)
VALUES(1,'בן'),
      (2,'בת');



DROP TABLE IF EXISTS `Goal`;

CREATE TABLE `Goal` (
    `CodeGoal` INTEGER PRIMARY KEY,
    `NameGoal` VARCHAR(255)
) CHARACTER SET 'UTF8';


-- The free trial of MDB ACCDB Viewer exports only half of the records in each table.
INSERT INTO `Goal`(`CodeGoal`,`NameGoal`)
VALUES(1,'להוריד שומן');



DROP TABLE IF EXISTS `Levels`;

CREATE TABLE `Levels` (
    `CodeLevel` INTEGER PRIMARY KEY,
    `NameLevel` VARCHAR(255)
) CHARACTER SET 'UTF8';


-- The free trial of MDB ACCDB Viewer exports only half of the records in each table.
INSERT INTO `Levels`(`CodeLevel`,`NameLevel`)
VALUES(1,'מתחיל'),
      (2,'מתקדם'),
      (3,'מבין');



DROP TABLE IF EXISTS `LevelStart`;

CREATE TABLE `LevelStart` (
    `CodeLevelStart` INTEGER PRIMARY KEY,
    `NameLevelStart` VARCHAR(255)
) CHARACTER SET 'UTF8';


-- The free trial of MDB ACCDB Viewer exports only half of the records in each table.
INSERT INTO `LevelStart`(`CodeLevelStart`,`NameLevelStart`)
VALUES(1,'מתחיל'),
      (2,'מתקדם'),
      (3,'מבין');



DROP TABLE IF EXISTS `Messages`;

CREATE TABLE `Messages` (
    `Froms` INTEGER PRIMARY KEY,
    `To` INTEGER,
    `Date` VARCHAR(255),
    `TheMessage` VARCHAR(255)
) CHARACTER SET 'UTF8';


-- The free trial of MDB ACCDB Viewer exports only half of the records in each table.
INSERT INTO `Messages`(`Froms`,`To`,`Date`,`TheMessage`)
VALUES(207799832,314713652,'12/2/2017','אשמח שתבנה לי תוכנית אימונים'),
      (314713652,207799832,'12/2/2017','אבנה לך בזמן המתקדם');



DROP TABLE IF EXISTS `Presence`;

CREATE TABLE `Presence` (
    `UserId` INTEGER,
    `NumberOF` INTEGER,
    `From` VARCHAR(255),
    `To` VARCHAR(255)
) CHARACTER SET 'UTF8';


-- The free trial of MDB ACCDB Viewer exports only half of the records in each table.
INSERT INTO `Presence`(`UserId`,`NumberOF`,`From`,`To`)
VALUES(314713652,0,'12/2/12','12/2/23'),
      (309238871,0,'25/06/2017 09:33:20','25/06/2017 09:33:12');



DROP TABLE IF EXISTS `Ranks`;

CREATE TABLE `Ranks` (
    `RankCode` INTEGER PRIMARY KEY,
    `RankName` VARCHAR(255)
) CHARACTER SET 'UTF8';


-- The free trial of MDB ACCDB Viewer exports only half of the records in each table.
INSERT INTO `Ranks`(`RankCode`,`RankName`)
VALUES(0,'מתאמן'),
      (1,'מאמן');



DROP TABLE IF EXISTS `Trainers`;

CREATE TABLE `Trainers` (
    `CodeTrainer` INTEGER PRIMARY KEY,
    `Specialty` VARCHAR(255),
    `Description` VARCHAR(255)
) CHARACTER SET 'UTF8';


-- The free trial of MDB ACCDB Viewer exports only half of the records in each table.
INSERT INTO `Trainers`(`CodeTrainer`,`Specialty`,`Description`)
VALUES(207799832,'אירובי','ריצות ופעילות שנעשת בכל דרך של הזזת הגוף הוא כאן!');



DROP TABLE IF EXISTS `Users`;

CREATE TABLE `Users` (
    `Id` INTEGER PRIMARY KEY,
    `Name` VARCHAR(255),
    `LastName` VARCHAR(255),
    `Pelepone` VARCHAR(255),
    `NumCity` INTEGER,
    `Thisdata` VARCHAR(255),
    `Password` VARCHAR(255),
    `Date` VARCHAR(255),
    `Gender` INTEGER,
    `Weight` INTEGER,
    `Height` INTEGER,
    `LevelStart` INTEGER,
    `LevelNow` INTEGER,
    `Goal` INTEGER,
    `Trainer` INTEGER,
    `Rank` INTEGER,
    `Itkadmot` INTEGER
) CHARACTER SET 'UTF8';


-- The free trial of MDB ACCDB Viewer exports only half of the records in each table.
INSERT INTO `Users`(`Id`,`Name`,`LastName`,`Pelepone`,`NumCity`,`Thisdata`,`Password`,`Date`,`Gender`,`Weight`,`Height`,`LevelStart`,`LevelNow`,`Goal`,`Trainer`,`Rank`,`Itkadmot`)
VALUES(808080808,'דני','דנון',NULL,3,NULL,'11111111',NULL,1,23,122,1,4,2,207799832,1,3),
      (123456789,'יובל','דנ','0986666666',3,NULL,'12345678',NULL,2,22,200,1,3,2,207799832,0,2),
      (678876559,'שיר','מלכה',NULL,3,NULL,'1122334455',NULL,2,56,167,3,6,2,207799832,0,3);



DROP TABLE IF EXISTS `WeightHeight`;

CREATE TABLE `WeightHeight` (
    `Id` INTEGER,
    `DateWeight` VARCHAR(255),
    `NumberOf` INTEGER,
    `Weight` INTEGER,
    `Height` INTEGER,
    PRIMARY KEY ( `Id`, `DateWeight`, `NumberOf` )
) CHARACTER SET 'UTF8';


-- The free trial of MDB ACCDB Viewer exports only half of the records in each table.
INSERT INTO `WeightHeight`(`Id`,`DateWeight`,`NumberOf`,`Weight`,`Height`)
VALUES(314713652,'12/1/2017',1,50,170),
      (314713652,'13/4/2017',2,55,171);



DROP TABLE IF EXISTS `WorkOnTa`;

CREATE TABLE `WorkOnTa` (
    `CodeWork` INTEGER PRIMARY KEY,
    `NameWork` VARCHAR(255)
) CHARACTER SET 'UTF8';


-- The free trial of MDB ACCDB Viewer exports only half of the records in each table.
INSERT INTO `WorkOnTa`(`CodeWork`,`NameWork`)
VALUES(1,'רגליים'),
      (2,'חזה'),
      (3,'גב'),
      (4,'כתפיים');


